# Generated by Django 5.2.3 on 2025-06-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='max_guests',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
