# Generated by Django 5.2.3 on 2025-06-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to='blog_images/'),
        ),
    ]
